/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.35
 * Generated at: 2021-08-01 12:50:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.homeinsurance.entities.AdminUser;

public final class signup_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/components/common_css_js.jsp", Long.valueOf(1627560726089L));
    _jspx_dependants.put("/components/navbar.jsp", Long.valueOf(1627821292073L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.homeinsurance.entities.AdminUser");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <!-- Required meta tags -->\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <title>Sign Up</title>\r\n");
      out.write("    ");
      out.write("<!-- Bootstrap CSS -->\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css\"\r\n");
      out.write("\trel=\"stylesheet\"\r\n");
      out.write("\tintegrity=\"sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC\"\r\n");
      out.write("\tcrossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Javascript -->\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("\tintegrity=\"sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM\"\r\n");
      out.write("\tcrossorigin=\"anonymous\"></script>\r\n");
      out.write("\t\r\n");
      out.write("<script src=\"https://kit.fontawesome.com/de4c62eee8.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("<script src=\"js/script.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("  \t");
      out.write('\r');
      out.write('\n');

	AdminUser adminUser = (AdminUser)session.getAttribute("current-user");

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-dark bg-dark\">\r\n");
      out.write("  <div class=\"container-fluid\">\r\n");
      out.write("    <a class=\"navbar-brand\" href=\"index.jsp\" style=\"font-size: 24px\"><b><i><u>EMS Portal</u></i></b></a>\r\n");
      out.write("    <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("      <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("    </button>\r\n");
      out.write("    <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("      <ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">\r\n");
      out.write("       <!--  <li class=\"nav-item\">\r\n");
      out.write("          <a class=\"nav-link active\" aria-current=\"page\" href=\"#\">Home</a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("          <a class=\"nav-link\" href=\"#\">Link</a>\r\n");
      out.write("        </li> -->\r\n");
      out.write("      </ul>\r\n");
      out.write("      \r\n");
      out.write("       <ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("       \r\n");
      out.write("       ");
 if(adminUser == null)
       { 
      out.write("\r\n");
      out.write("\t        <li class=\"nav-item text-right\">\r\n");
      out.write("\t          <a class=\"nav-link\" aria-current=\"page\" href=\"login.jsp\"><i class=\"fa fa-sign-in mx-1\" style=\"font-size: 24px\"><b>Login</b></i></a>\r\n");
      out.write("\t        </li>\r\n");
      out.write("\t        <li class=\"nav-item text-right\">\r\n");
      out.write("\t          <a class=\"nav-link\" aria-current=\"page\" href=\"signup.jsp\"><i class=\"fa fa-user\" style=\"font-size: 24px\"><b>Register</b></i></a>\r\n");
      out.write("\t        </li>\r\n");
      out.write("        ");
}
        else { 
      out.write("\r\n");
      out.write("        \t<li class=\"nav-item active\">\r\n");
      out.write("\t\t\t    <a class=\"nav-link\" href=\"admin.jsp\"><b>");
      out.print( adminUser.getAdminName() );
      out.write("</b></a>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t      \t\r\n");
      out.write("\t\t\t<li class=\"nav-item active\">\r\n");
      out.write("\t\t\t     <a class=\"nav-link\" href=\"LogoutServlet\"><b>Logout</b></a>\r\n");
      out.write("\t\t\t </li>\r\n");
      out.write("        ");
} 
      out.write("\r\n");
      out.write("       </ul>\r\n");
      out.write("      \t\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</nav>");
      out.write("\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("    \t<div class=\"row my-5\">\r\n");
      out.write("    \t\t<div class=\"col-md-6 offset-md-3\">\r\n");
      out.write("    \t\t\t<h1><u><b>Sign-Up</b></u></h1>\r\n");
      out.write("    \t\t\t<form action=\"SignupServlet\" method=\"post\">\r\n");
      out.write("\t\t\t\t  <div class=\"mb-3\">\r\n");
      out.write("\t\t\t\t    <label for=\"exampleInputEmail1\" class=\"form-label\">Name</label>\r\n");
      out.write("\t\t\t\t    <input type=\"name\" class=\"form-control\" id=\"name\" aria-describedby=\"emailHelp\" name=\"name\" placeholder=\"Enter Your Name\" required>\r\n");
      out.write("\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t  <div class=\"mb-3\">\r\n");
      out.write("\t\t\t\t    <label for=\"exampleInputEmail1\" class=\"form-label\">Email address</label>\r\n");
      out.write("\t\t\t\t    <input type=\"email\" class=\"form-control\" id=\"email\" aria-describedby=\"emailHelp\" name=\"email\" placeholder=\"Enter Email\" required>\r\n");
      out.write("\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t  <div class=\"mb-3\">\r\n");
      out.write("\t\t\t\t    <label for=\"exampleInputPassword1\" class=\"form-label\">Password</label>\r\n");
      out.write("\t\t\t\t    <input type=\"password\" class=\"form-control\" id=\"password\" name=\"password\" placeholder=\"Enter Password\" required>\r\n");
      out.write("\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t  <div class=\"mb-3\">\r\n");
      out.write("\t\t\t\t  \t<input type=\"radio\" id=\"admin\" name=\"userType\" value=\"admin\">\r\n");
      out.write("\t\t\t\t  \t<label for=\"admin\">Admin</label>\r\n");
      out.write("\t\t\t\t  \t<input type=\"radio\" id=\"normal\" name=\"userType\" value=\"normal\">\r\n");
      out.write("\t\t\t\t  \t<label for=\"normal\">Normal</label>\r\n");
      out.write("\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t  <button type=\"submit\" class=\"btn btn-primary\">Submit</button>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t\t</div>\r\n");
      out.write("    \t</div>\r\n");
      out.write("    \t\r\n");
      out.write("    </div>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
